---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Update the repository
    package:
      update_cache: yes


- hosts: all
  become: true
  roles:
    - apache
    - git


- hosts: all
  become: true
  tasks:
  - name: Remove the default index.html page
    file:
      path: /var/www/html
      state: absent


- hosts: all
  become: true
  tasks:
  - name: Clone git repo
    git:
      repo: https://github.com/oyewoledavid/Zuri-Landiing-Page.git
      dest: /var/www/html
